apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qq8yfvtku-go 
  janus-idp.io/tekton: qq8yfvtku-go
  backstage.io/kubernetes-id: qq8yfvtku-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qq8yfvtku-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  